Add condition for if file is non-existent

diff --git a/amp/bin/amp b/amp/bin/amp
--- a/amp/bin/amp
+++ b/amp/bin/amp
@@ -18,13 +18,18 @@ then
     if [ $(find *.cpp) -z ]; then
       printf "\033[0;31m== \033[1;37mNo .cpp files found.\033[0m\n"
     else
-      #printf "\033[1;31mCaution: \033[1;37mAssuming there are just two .cpp files.\033[0m\n"
       for file in "$(ls *.cpp)"; do
         g++ -o $file-amp $file
       done
-      #g++ -o main $(find *.cpp | head -n 1)
-      #g++ -o main1 $(find *.cpp | head -n 2 | tail -n 1)
-      echo "Wait 2s"; sleep 2; printf "\033[0;32m== \033[1;37m Build Successful!\033[0m\n"
+      case "$?" in
+        0)
+          printf "\033[0;32m== \033[1;37m Build Successful!\033[0m\n"
+          ;;
+        *)
+          printf "\e[1;31mError in compiling. Exiting.\e[0m\n"
+          exit 563
+          ;;
+      esac
     fi
     fi
 fi
